name: 'VulnCheck Actions'
description: 'Integrate VulnCheck into your GitHub Actions workflow'
author: 'Kevin Olson <kolson@vulncheck.com>'
branding:
  icon: 'shield'
  color: gray-dark

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  token:
    description: 'VulnCheck Token'
    required: true
  command:
    description: 'Command to run'
    default: 'scan'
  scan_cvss_base_threshold:
    description: 'CVSS Threshold to fail the workflow'
    required: false
  scan_cvss_temporal_threshold:
    description: 'CVSS Temporal Threshold to fail the workflow'
    required: false
outputs:
  scan-output:
    description: 'Output results if a scan is run'
  scan-count:
    description: 'Output count of vulnerabilities if a scan is run'
  scan-signature:
    description: 'SHA256 hash of the scan results (used to detect change)'
runs:
  using: node20
  main: dist/index.js
