name: 'VulnCheck Action'
description: 'Integrate VulnCheck into your GitHub Actions workflow'
author: 'Kevin Olson <kolson@vulncheck.com>'
branding:
  icon: 'shield'
  color: gray-dark

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  token:
    description: 'VulnCheck Token'
    required: true
  command:
    description: 'Command to run'
    default: 'scan'
  scan-path:
    description: 'Path to scan'
    required: false
    default: './'
  scan-cvss-base-threshold:
    description: 'CVSS Threshold to fail the workflow'
    required: false
  scan-cvss-temporal-threshold:
    description: 'CVSS Temporal Threshold to fail the workflow'
    required: false
  scan-cve-details:
    description:
      'Include an annotation for every found CVE showing package type,
      cataloger, and locations'
    required: false
  scan-cve-npm-rel:
    description: 'Attempt to use npm to trace CVE package to its owner'
    required: false
outputs:
  scan-output:
    description: 'Output results if a scan is run'
  scan-count:
    description: 'Output count of vulnerabilities if a scan is run'
  scan-signature:
    description: 'SHA256 hash of the scan results (used to detect change)'
runs:
  using: node20
  main: dist/index.js
