name: 'VulnCheck Actions'
description: 'Integrate VulnCheck into your GitHub Actions workflow'
author: 'Kevin Olson <kolson@vulncheck.com>'
branding:
  icon: 'shield'
  color: gray-dark

inputs:
  token:
    description: 'VulnCheck Token'
    required: true
  cli_pat:
    description: 'A token with access to the CLI'
    required: true
  scan_cvss_base_threshold:
    description: 'CVSS Threshold to fail the workflow'
    required: false
  scan_cvss_temporal_threshold:
    description: 'CVSS Temporal Threshold to fail the workflow'
    required: false
runs:
  using: node20
  main: dist/index.js
