name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: write-all

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          token: ${{ secrets.VC_TOKEN }}

      - name: Retrieve Output
        id: output
        run: |
          echo "${{ steps.test-action.outputs.scan-count }}"
          echo "${{ steps.test-action.outputs.scan-signature }}"
          echo "${{ steps.test-action.outputs.scan-output }}"
